### ISSUE TITLE
[회의록] 2022-04-06

### ISSUE THREAD

**Issue by hyun98** [JO2SEO/AOMD#1]
## :pushpin: Subject
> "블록체인 기반 클라우드 로그 관리 플랫폼”을 주제로 교수님과의 첫 번째 미팅

## :scroll: Content
1. 교수님과의 회의는 주에 1번 or 2주에 1번 
2. 다음 번 미팅은 우리가 다 시간되고 주제가 어느 정도 픽스됐을 때 교수님께 이메일 드리고 날짜 시간 잡기.
3. < 클라우드 환경에서 블록체인 기반의 웹서버 로그 관리 시스템 - 손 용 범⋅김 영 학 >
해당 논문에서 문제점(취약점)을 찾고 그걸 해결하기 위한 방안을 찾아보기 
4. 교수님께서 주신 힌트 : 로그를 이용해서 악의적인 목적으로 공격을 시도할 때, 공격자는 자신의 진입 경로(접근 로그)를 없애고 싶어한다. 하지만 클라우드 환경에서는 그 정보(웹 서버 접근 로그)들이 분산 처리, 저장되어 있기 때문에 어느 하나의 특정 디비에서만 그 정보를 지워도 다른 곳에서 열람이 가능하고 공격자 추적이 가능하다.
5. 결론 : 시중에 나와있는 논문을 참고하되 해당 내용을 토대로 우리가 발전시킬 수 있는 방향, 논문과의 차별점을 찾아야 함

**Comment by jwseo4074** [comment]
It's so cool!
