### ISSUE TITLE
[면담] 2022-04-11

### ISSUE THREAD

**Issue by whquddn55** [JO2SEO/AOMD#3]
## :pushpin: Subjects
> 1. 교수님 지정주제
> 2. 자유주제에 대한 피드백

<br>

## :scroll: Contents
# 교수님 지정주제
### 1. 로봇 시스템을 대상으로 한 악성 행위 탐지 기술

로봇을 제어하는 OS인 ROS의 취약점을 분석하고, 탐지하는 기술을 개발하는 과제.
기존 ROS(v1)에서의 연구는 활발이 이루어져 있으나, ROS(v2)가 릴리즈 된 이후의 연구는 진행되지 않는 것으로 보임(교수님 의견).

ROS를 로봇팔을 예로 들어 설명해주셨는데, 팔꿈치(A)가 움직인 뒤 팔목(B)가 움직이고, 팔목(B)가 움직인 뒤 손가락(C)가 움직이는 log를 남기는게 첫 과제, 그 log를 분석해서 취약점을 탐지하는 것이 두 번째 과제라고 하심.
log를 남기는 것은 ROS내에서 기능을 제공할 거라 사용 방법만 익히면 되고, 취약점을 탐지하는 것은 여러 방법이 있다고 설명해주심.

첫 번째로, 단순히 Rule-base로 (A이후에 C가 오면 안 된다)식으로 Rule를 정해두고 탐지해야함. => 너무 간단하기 때문에 이것만으로는 부족함
두 번째로, ML을 써서 탐지하는 방법이 있음. => 세명 다 ML에 무지하고, 관심이 크게 없음.

=> ROS, 취약점, ML 모두 처음 접하거나 접하기만 해본 수준이라 어려울 것이라 판단

### 2. 웹 어셈블리를 위한 Secure Memory Allocator 기술 개발

C에서는 UAF에 대한 연구가 활발이 이루어져 있고, 그것을 방지할 여러 대책이 연구되어 사용되고 있음.
예를 들어, free(p)를 할 경우 p와 binding된 포인터들을 모두 null로 바꾸어주어 접근이 불가능하게 하는 방법이 있음.
최근 웹에서 빠르게 중요성을 알리고 있는 WASM에는 이렇게 안전하게 메모리를 Allocate시켜주는 시스템이 없는 것으로 보임(교수님 의견). 
따라서, WASM에서 Secure Memory Allocator를 구현할 방법을 연구하고 개발하는 과제.

=> Static으로 감지하든 Dynamic하게 감지하든 컴파일러에 대한 깊은 지식이 요구될 것으로 보여서 어려울 것이라 판단

# 자유주제에 대한 피드백
1. 왜 블록체인을 쓰는 지 모르겠음(= 왜 필요한 서비스인지 모르겠음)
2. 사용자가 임의로 자신의 포트폴리오를 업로드할 경우 어떻게 걸러낼 지 모르겠음
3. 기존에 나온 플랫폼들과 다른 무엇을 만들기 힘들다면 성능상으로 개선하거나 더 최신기술을 사용해서 적용해보는 방식으로 접근하는게 좋아보임

**Comment by hyun98** [comment]
- 성능 최적화
- 확장성 있는 설계

이런 부분에서 차별점을 둬야 될 것 같아요
어렵겠지만 해봅시당

**Comment by jwseo4074** [comment]
자료 정리 한다고 고생하셨습니다! 

성능 최적화... 할 수 있습니다
필승 i can do
