### ISSUE TITLE
[면담] 2022-05-09

### ISSUE THREAD

**Issue by whquddn55** [JO2SEO/AOMD#5]
## :pushpin: Subjects
> 
1. 주제 피드백
2. 교수님 대면 미팅은 앞으로 2주에 1번 => 조교님과 상의해서 미팅 날짜 및 시간 잡기 (조교님이 메일 주신다고 함)
3. 주제 이정도로 충분하고 이제 본격적으로 개발 시작
<br>

## :scroll: Contents
1. URL로 제공될 경우, URL 브루트포스 공격이 들어올 수도 있으니 어떻게 막아야할지 고민해봐야함 ( 쿼리문 자체에 시간 제약을 걸어 브루트 포스 공격이 불가하게 하는 방법을 예로 들어 )

    < 받을 수 있는 공격의 종류 >
* 네트워크를 아예 망가뜨리기 위한 목적
* DDos 공격 - 리퀘스트 포화
* 다른 사람인 척하고 공격 
각각의 공격에 대해 시나리오를 작성하고 방어 대책을 강구하여 발표하면 좋을 것 같다고 하심.

2. 최근 학력 블라인드로 채용하는 것이 유행이니 학력정보나 관련 개인정보를 기업이 무조건 다 볼수 있도록 하는 것이 아니라 개인이 정보를 컨트롤할 수 있도록 고려해야함. ( 데이터의 무결성만이 아니라 개인 프라이버시의 보호에도 중점을 두고 진행 )

3. 굳이 블록체인을 개선할 필요없이 도구로만 사용해도 되고, 백엔드쪽에 기술적 고민을 해도 됨. ( 기존에는 어떤 문제가 있었는가 ? 서비스를 개선하기 위해 어떤 노력을 하였는가 ? => 고민의 흔적을 최대한 남겨두기 )

**Comment by hyun98** [comment]
교수님이 보안쪽 전공하시니까
우리가 어느정도 만들때마다 교수님께 취약점을 계속 피드백 받아서 개선해야겠다고 생각중

**Comment by jwseo4074** [comment]
미팅 때 들었던거 위주로 내용 조금 추가해놨습니다. 확인해보시고 괜찮으면 바로 close 합시다!
