### ISSUE TITLE
[면담] 2022-07-04

### ISSUE THREAD

**Issue by jwseo4074** [JO2SEO/AOMD#8]
## :pushpin: Subjects
> 7/4 교수님 미팅

<br>

### Front-end

비슷한 주제로 과제를 하는 다른 팀들과의 차별점(기존에 있는 서비스와의 차별점)으로 사용자 경험(UX/UI)를 강조하심
⇒  드래그 앤 드랍, 자기소개서 편집 및 저장

DND에서 발생하는 세부적인 이슈는 기본적인 것들(필요한  기능들의 전체적인 폼) 먼저 구현해놓고 세부적인 이슈 내용은 나중에 시간 될 때 다시 다듬으라는 피드백
⇒ DND는 이쯤 해두고 다른 요소들 먼저 구현(다른 팀들과의 차별점 → 마크다운 기능, 리덕스 적용)

백엔드와 진행과정을 공유하면서 같이 협업해야하는 부분이 있을 수 있으니 한 가지(DND key 값에 따라 다른 다른 항목이 드래그 되는 이슈)에 목메면 안되고 전체적인 흐름을 보라는 피드백

해야 할 일 : props로 데이터 주고 받고 했던 프로세스 전반적인 내용 ⇒ 리덕스 이용해서 리덕스 스토어에 모든 데이터를 저장하는 걸로 해보기( 이때 리덕스 스토어에 소셜 로그인 시 백엔드에서 받아오는 jwt 토큰까지 저장 ⇒ 토큰을 props 로 계속 넘겨주면서 프로세스를 진행할 수는 없지 않은가 )

--- 

### Back-end

1. 블록체인에 너무 목매지말고, 얼른 끝내고 서비스 적인 측면에서 기존의 아이디어들 보다 더 발전 시킬 수 있는 방법을 도모했으면 좋겠음(저번 졸업과제 때 거의 동일한 주제가 있었음. 저번 졸업과제에는 QR코드를 통해서 접근성을 높혔음)
2. 서버관점에서 스케일아웃을 할 수 있다거나, 보안쪽으로 더 강화할 수 있는 방법을 도모해봐도 좋을 것 같음(예를 들어, 모듈이 n개 있을 때 하나의 모듈의 권한이 탈취당했을 때 다른 모듈의 기능을 이용해서 많은 작업을 할 수 있기 때문에 모듈별 권한을 강력하게 제한하는 방법)

(피드백)

1. 여러 기관이 학력을 발급하게 될 것인데, 기관이 블록체인에 write 뿐만 아니라 read도 할 수 있으면 발급 기관이 개인정보를 가져갈 수 있는 문제가 발생 할 수 있을 것 같음. 만약 write권한만 부여하고 read를 제한할 수 있다면 제한 하는게 맞을 지. => 블록체인에서 그런 방법을 지원해주는 지 모르겠지만 고민해볼 법 하네요 허허

**Comment by whquddn55** [comment]
이번 주 까지 한번 블록체인 끝내보...

**Comment by jwseo4074** [comment]
이번 주 까지 리덕스 끝내보...

**Comment by hyun98** [comment]
스케일아웃 방법 생각해 보...ㄹ게요.. 죄성함다
